# Generated by Django 5.1.4 on 2026-05-06 12:57

import apps.users.utils.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cover_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('LIVE', 'Live'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=500)),
                ('cover_url', models.CharField(blank=True, max_length=500, null=True)),
                ('version', models.IntegerField(default=1)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PRODUCER', 'Producer'), ('COMPOSER', 'Composer'), ('VOCALIST', 'Vocalist'), ('MANAGER', 'Manager'), ('ARTIST', 'Artist'), ('OTHER', 'Other')], max_length=12)),
                ('split_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_collaborator_per_project')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('TRACK_UPLOADED', 'Track Uploaded'), ('COLLAB_JOINED', 'Collaborator Joined'), ('DISTRIBUTED', 'Distributed'), ('EXPENSE_LOGGED', 'Expense Logged'), ('REVENUE_RECEIVED', 'Revenue Received'), ('PAYOUT_SENT', 'Payout Sent')], max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_ac_project_944346_idx')],
            },
        ),
    ]
