import type { CapacitorConfig } from "@capacitor/cli";

// Auto-generated by bin/dev-mobile.sh — do not edit by hand. Re-run the script
// after switching networks to update the URL.
const config: CapacitorConfig = {
  appId: "dev.musiky.app",
  appName: "Musiky",
  webDir: "public",
  // Match the WebView scheme to the actual URL so a clear-data wipe doesn't
  // leave behind an https://localhost/ origin in the navigation history.
  server: {
    url: "http://192.168.43.10:3000",
    cleartext: true,
    androidScheme: "http",
  },
  android: {
    allowMixedContent: true,
    webContentsDebuggingEnabled: true,
  },
};

export default config;
