# Generated by Django 5.1.4 on 2026-05-06 12:57

import apps.users.utils.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('plan', models.CharField(choices=[('STARTER', 'Starter'), ('PRO', 'Pro'), ('TEAM', 'Team')], default='STARTER', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
