# Generated by Django 5.1.4 on 2026-05-06 12:57

import apps.users.utils.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('PRODUCTION', 'Production'), ('MASTERING', 'Mastering'), ('VIDEO', 'Video'), ('LEGAL', 'Legal'), ('OTHER', 'Other')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('spent_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='distribution.platform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts_received', to=settings.AUTH_USER_MODEL)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='finance.revenue')),
            ],
        ),
        migrations.AddIndex(
            model_name='revenue',
            index=models.Index(fields=['project', '-received_at'], name='finance_rev_project_451e85_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['user', 'status'], name='finance_pay_user_id_6dc9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['project'], name='finance_pay_project_4e422e_idx'),
        ),
    ]
