# Generated by Django 5.1.4 on 2026-05-06 12:57

import apps.users.utils.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.CharField(default=apps.users.utils.ids.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('LIVE', 'Live')], default='PENDING', max_length=8)),
                ('live_at', models.DateTimeField(blank=True, null=True)),
                ('streams', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='projects.project')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='distribution.platform')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'platform'), name='uniq_distribution_per_project_platform')],
            },
        ),
    ]
